version: "3"
services:
  trellis:
    image: trellisldp/trellis-postgresql:latest
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db/trellis
      QUARKUS_DATASOURCE_USERNAME: trellis
      QUARKUS_DATASOURCE_PASSWORD: trellis
      TRELLIS_HTTP_WEAK_ETAG: "false"
      TRELLIS_HTTP_MEMENTO_HEADER_DATES: "false"
      TRELLIS_HTTP_PRECONDITION_REQUIRED: "true"
      TRELLIS_JDBC_LDP_TYPE: "true"
    ports:
      - 80:8080
    depends_on:
      - db
    volumes:
      - ./.trellis_data:/opt/trellis/data
      - ./.trellis_log:/opt/trellis/log
      # Please see note below about the ./etc directory
      # - /local/trellis/etc:/opt/trellis/etc
  db:
    image: postgres
    environment:
      POSTGRES_DB: trellis
      POSTGRES_PASSWORD: trellis
      POSTGRES_USER: trellis
      PGDATA: /var/lib/postgresql/data/pgdata/mydata
    volumes:
      - ./.postgresql_data:/var/lib/postgresql/data/pgdata/mydata
